# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master


stages:
- stage: Build
  jobs:
    - job: Build
      pool:
        vmImage: 'ubuntu-latest'

      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.SourcesDirectory)'
          artifact: 'drop'
          publishLocation: 'pipeline'
      #- script: |
      #    npm install
      #    npm run build
      #  displayName: 'npm install and build'

      # - script: |
      #     npm run test-juint
      #   displayName: 'npm test'



      # - task: PublishTestResults@2
      #   condition: succeededOrFailed()
      #   inputs:
      #     testResultsFormat: 'JUnit'
      #     testResultsFiles: '**/test-results.xml'
- stage: Release
  dependsOn: Build
  jobs:
    - deployment: Release
      pool:
        vmImage: 'ubuntu-latest'
      environment: 'npm'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: Npm@1
              displayName: 'npm publish'
              inputs:
                command: publish
                workingDir: '$(Pipeline.Workspace)/drop'
                verbose: false
                publishEndpoint: NPMJS